name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true
      after-version:
        description: 'Next version number to set after release'
        required: true

jobs:
  set-release-version:
    uses: BX-Team/Quark/.github/workflows/set-version.yml@master
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  publish:
    needs: set-release-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: COMMIT
          toTag: ${{ github.ref }}
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "commit_template": "- [`#{{SHORT_MERGE_SHA}}`](https://github.com/BX-Team/Quark/commit/#{{MERGE_SHA}}) #{{TITLE}}",
              "categories": [
                {
                    "title": "## üöÄ Features",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## üêõ Fixes",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## üèéÔ∏è Performance",
                    "labels": ["perf"]
                },
                {
                    "title": "## üèó Refactor",
                    "labels": ["refactor"]
                },
                {
                    "title": "## üìù Documentation",
                    "labels": ["docs"]
                },
                {
                    "title": "## üî® Build",
                    "labels": ["build", "chore", "ci"]
                },
                {
                    "title": "## üíÖ Style",
                    "labels": ["style"]
                },
                {
                    "title": "## üí¨ Other",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ],
              "custom_placeholders": [
                {
                  "name": "SHORT_MERGE_SHA",
                  "source": "MERGE_SHA",
                  "transformer": {
                    "pattern": "^([0-9a-f]{7})[0-9a-f]*$",
                    "target": "$1"
                  }
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          tag_name: v${{ inputs.version }}
          generate_release_notes: false
          draft: false
          prerelease: false
          target_commitish: master
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          name: Quark ${{ inputs.version }}
          preserve_order: true

      - name: Publish to BX Team Maven Repository
        continue-on-error: true
        run: ./gradlew publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_SECRET }}

  set-after-version:
    needs: publish
    uses: BX-Team/Quark/.github/workflows/set-version.yml@master
    with:
      version: ${{ inputs.after-version }}
    secrets: inherit
